import React, { useEffect, useState } from 'react';
import * as Notifications from 'expo-notifications';
import { Alert, Pressable, SafeAreaView, Text, View } from 'react-native';
import { createNavigationContainerRef, NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { api, ApiError } from './api';
import { authStore, jsonStore, SHELTER_QUEUE, SOS_QUEUE } from './storage';
import { acquireLocation, SetuLocation } from './location';
import { queueShelterEvent, queueSos, subscribeNetwork, syncSosQueue, NetworkMode } from './offline';
import { Button, Card, colors, ErrorState, Field, Loading, Screen, Status, styles, Title } from './ui';
import { CitizenMap, EnhancedMember, EnhancedShelter, NotificationDetail } from './featureScreens';
import { CitizenSosStatus, EnhancedCitizenSos, EnhancedLeader } from './enhancedFlows';
import { deactivateRegisteredDevice, registerForNotifications, subscribeToTokenRefresh, targetFromNotification, NotificationTarget } from './notifications';

type User = { userId: string; name?: string; role: string; mobile?: string; shelterId?: string; teamId?: string };
const Stack = createNativeStackNavigator(); const Tabs = createBottomTabNavigator();
const navigationRef = createNavigationContainerRef<any>();
const roleLabels: Record<string, string> = { USER: 'Citizen', SHELTER_ADMIN: 'Shelter Admin', RESCUE_LEADER: 'Rescue Leader', RESCUE_MEMBER: 'Rescue Member' };

function NotificationBootstrap({ user }: { user: User | null }) {
  const [pending, setPending] = useState<NotificationTarget | null>(null);
  useEffect(() => {
    if (!user) return;
    registerForNotifications().catch(() => undefined);
    const tokenRefresh = subscribeToTokenRefresh(() => undefined);
    const response = Notifications.addNotificationResponseReceivedListener((response) => {
      setPending(targetFromNotification(response.notification));
    });
    Notifications.getLastNotificationResponseAsync().then((response) => {
      if (response) setPending(targetFromNotification(response.notification));
    }).catch(() => undefined);
    return () => { response.remove(); tokenRefresh.remove(); };
  }, [user]);
  useEffect(() => {
    if (pending && user && navigationRef.isReady()) {
      navigationRef.navigate('Notification', pending);
      setPending(null);
    }
  }, [pending, user]);
  return null;
}

function AuthScreen({ onAuthenticated }: { onAuthenticated: (data: any) => void }) {
  const [mode, setMode] = useState<'citizen' | 'staff'>('citizen'); const [mobile, setMobile] = useState(''); const [code, setCode] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit() { setBusy(true); setError(''); try { const data = mode === 'citizen' ? sent ? await api.verifyOtp({ mobile, code }) : await api.otp(mobile) : await api.login(email, password); if (mode === 'citizen' && !sent) { setSent(true); Alert.alert('Demo OTP', `The existing backend returned: ${data.devOtp}`); } else { await authStore.set(data.token); onAuthenticated(data.user); } } catch (e) { setError(e instanceof Error ? e.message : 'Authentication failed'); } finally { setBusy(false); } }
  return <Screen><View style={{ marginTop: 50, gap: 10 }}><Text style={styles.eyebrow}>SETU / EMERGENCY RESPONSE</Text><Text style={styles.title}>One bridge to safety.</Text><Text style={styles.subtitle}>Sign in to live disaster information and response operations.</Text></View><Card><View style={{ flexDirection: 'row', gap: 8 }}><Button label="Citizen OTP" onPress={() => { setMode('citizen'); setSent(false); }} /><Button label="Staff login" onPress={() => setMode('staff')} /></View>{mode === 'citizen' ? <><Field value={mobile} onChangeText={setMobile} placeholder="10-digit mobile number" keyboardType="phone-pad" />{sent && <Field value={code} onChangeText={setCode} placeholder="OTP" keyboardType="number-pad" />}</> : <><Field value={email} onChangeText={setEmail} placeholder="Staff email" keyboardType="email-address" /><Field value={password} onChangeText={setPassword} placeholder="Password" secureTextEntry /></>}{error ? <Text style={styles.error}>{error}</Text> : null}<Button label={busy ? 'Signing in...' : sent || mode === 'staff' ? 'Continue' : 'Send OTP'} onPress={submit} disabled={busy} /></Card><Text style={styles.subtitle}>Citizen OTP delivery is mocked by the existing backend. Never place server secrets in this app.</Text></Screen>;
}

function useNetwork() { const [mode, setMode] = useState<NetworkMode>('ONLINE'); useEffect(() => subscribeNetwork(setMode), []); return mode; }
function Header({ user, onLogout }: { user: User; onLogout: () => void }) { return <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><View><Text style={styles.eyebrow}>{roleLabels[user.role] || user.role}</Text><Text style={{ color: colors.ink, fontSize: 20, fontWeight: '800' }}>Namaste, {user.name || 'operator'}</Text></View><Pressable accessibilityLabel="Log out" onPress={onLogout}><Text style={{ color: colors.red, fontWeight: '800' }}>Log out</Text></Pressable></View>; }
function NetworkBanner({ mode }: { mode: NetworkMode }) { return mode === 'ONLINE' ? null : <View style={{ backgroundColor: colors.warningSurface, padding: 10, borderRadius: 6, borderWidth: 1, borderColor: colors.warningBorder }}><Text style={{ color: colors.warningText, fontWeight: '700' }}>{mode === 'OFFLINE' ? 'Offline: cached information only. No server action is confirmed.' : 'Degraded network: updates may be delayed.'}</Text></View>; }

function CitizenHome({ user, onLogout }: { user: User; onLogout: () => void }) { const mode = useNetwork(); const [alerts, setAlerts] = useState<any[]>([]); const [sos, setSos] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); async function load() { setLoading(true); setError(''); try { const [a, s] = await Promise.all([api.alerts(), api.mySos()]); setAlerts(a.alerts || a.events || []); setSos(s.sos || []); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load live status'); } finally { setLoading(false); } } useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []); return <Screen><Header user={user} onLogout={onLogout} /><NetworkBanner mode={mode} /><Title eyebrow="Citizen status">Stay informed. Stay connected.</Title>{loading ? <Loading /> : error ? <ErrorState message={error} retry={load} /> : <><Card><Status>{alerts.length ? 'Active alerts available' : 'No active alerts returned'}</Status><Text style={styles.subtitle}>No network or missing data never means safe. Check official alerts and emergency contacts.</Text></Card><Card><Text style={styles.label}>MY SOS CASES</Text><Text style={styles.metric}>{sos.length}</Text>{sos.slice(0, 2).map((item) => <View key={item.sosId}><Text style={{ color: colors.ink, fontWeight: '800' }}>{item.sosId} · {item.priority}</Text><Text style={styles.subtitle}>{item.status} · {item.acknowledged ? 'Server acknowledged' : 'Not acknowledged'}</Text></View>)}</Card><Card><Text style={styles.label}>ACTIVE WARNINGS</Text>{alerts.slice(0, 3).map((alert, i) => <Text key={alert.eventId || alert.notificationId || i} style={{ color: colors.ink }}>{alert.headline || alert.message || alert.title || 'Official alert'}</Text>)}{!alerts.length && <Text style={styles.subtitle}>No active emergencies were returned by SETU.</Text>}</Card></>}</Screen>; }


function Shelters() { const mode = useNetwork(); const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); async function load() { try { const location = await acquireLocation(); const data = await api.shelters(location?.latitude, location?.longitude); setRows(data.shelters || []); } catch (e) { setError(e instanceof Error ? e.message : 'Shelters unavailable'); } finally { setLoading(false); } } useEffect(() => { load(); }, []); return <Screen><NetworkBanner mode={mode} /><Title eyebrow="Shelter discovery">Nearby safe places</Title>{loading ? <Loading /> : error ? <ErrorState message={error} retry={load} /> : rows.length ? rows.map((s) => <Card key={s.shelterId}><Text style={{ color: colors.ink, fontSize: 18, fontWeight: '800' }}>{s.name}</Text><Status danger={['FULL', 'OVER_CAPACITY', 'CLOSED'].includes(s.status)}>{s.status}</Status><Text style={styles.subtitle}>{s.available} available of {s.capacity} · {s.distanceKm == null ? 'distance unavailable' : `${s.distanceKm} km`}</Text><Text style={styles.subtitle}>{s.stalenessNotice || 'Freshness not provided'}</Text></Card>) : <Card><Text style={styles.subtitle}>No shelter records were returned. This is not confirmation that no shelter exists.</Text></Card>}</Screen>; }

function CitizenTabs({ user, onLogout }: { user: User; onLogout: () => void }) { return <Tabs.Navigator screenOptions={{ headerShown: false, tabBarActiveTintColor: colors.teal }}><Tabs.Screen name="Home">{() => <CitizenHome user={user} onLogout={onLogout} />}</Tabs.Screen><Tabs.Screen name="Shelters" component={Shelters} /><Tabs.Screen name="Map" component={CitizenMap} /><Tabs.Screen name="SOS" component={EnhancedCitizenSos} /><Tabs.Screen name="SOS status" component={CitizenSosStatus} /></Tabs.Navigator>; }

function Leader({ user, onLogout }: { user: User; onLogout: () => void }) { const [dash, setDash] = useState<any>(); const [queue, setQueue] = useState<any[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function load() { try { const [d, q] = await Promise.all([api.rescueDashboard(), api.queue('?unassignedOnly=false')]); setDash(d); setQueue(q.sos || []); } catch (e) { setError(e instanceof Error ? e.message : 'Command centre unavailable'); } } useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []); async function assign(sos: any) { try { const rec = await api.recommendations(sos.sosId); const candidate = (rec.recommendations || []).find((r: any) => r.assignable); if (!candidate) return Alert.alert('No assignable team', 'The backend returned no AVAILABLE team.'); setBusy(true); await api.assign(sos.sosId, candidate.teamId, false); await load(); } catch (e) { Alert.alert('Assignment failed', e instanceof Error ? e.message : 'The server rejected this assignment.'); } finally { setBusy(false); } } return <Screen><Header user={user} onLogout={onLogout} /><Title eyebrow="Rescue command">Prioritize the next confirmed action.</Title>{error ? <ErrorState message={error} retry={load} /> : <><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>{[['Active SOS', dash?.counts?.totalActiveSos], ['P1', dash?.counts?.critical_P1], ['Unassigned', dash?.counts?.unassigned], ['Teams free', dash?.teams?.available]].map(([label, value]) => <Card key={String(label)}><Text style={styles.label}>{label}</Text><Text style={styles.metric}>{value ?? '—'}</Text></Card>)}</View>{queue.map((s) => <Card key={s.sosId}><Text style={{ color: colors.ink, fontWeight: '800' }}>{s.sosId} · {s.priority}</Text><Status>{s.status}</Status><Text style={styles.subtitle}>{s.emergencyType} · {s.peopleCount} people · {s.injuredCount} injured</Text>{['PENDING', 'TIMEOUT', 'VERIFIED'].includes(s.status) && <Button label={busy ? 'Assigning...' : 'Use backend recommendation'} onPress={() => assign(s)} disabled={busy} />}</Card>)}{!queue.length && <Card><Text style={styles.subtitle}>No active SOS returned. Missing data is never interpreted as no emergency.</Text></Card>}</>}</Screen>; }

function Member({ user, onLogout }: { user: User; onLogout: () => void }) { const [cases, setCases] = useState<any[]>([]); const [error, setError] = useState(''); async function load() { try { const data = await api.assigned(); setCases(data.sos || []); } catch (e) { setError(e instanceof Error ? e.message : 'Assignments unavailable'); } } useEffect(() => { load(); const timer = setInterval(load, 25000); return () => clearInterval(timer); }, []); async function action(id: string, kind: string) { try { if (kind === 'accept') await api.accept(id); else await api.status(id, kind, await acquireLocation()); await load(); } catch (e) { Alert.alert('Action rejected', e instanceof Error ? e.message : 'Backend rejected the state transition.'); } } return <Screen><Header user={user} onLogout={onLogout} /><Title eyebrow="Field operations">Your assigned emergencies</Title>{error ? <ErrorState message={error} retry={load} /> : cases.length ? cases.map((s) => <Card key={s.sosId}><Text style={{ color: colors.ink, fontWeight: '800' }}>{s.sosId} · {s.priority}</Text><Status>{s.status}</Status><Text style={styles.subtitle}>{s.emergencyType} · {s.peopleCount} people · {s.injuredCount} injured</Text><Text style={styles.subtitle}>Origin is preserved. Last known: {s.lastKnown?.latitude?.toFixed?.(4) || 'unknown'}, {s.lastKnown?.longitude?.toFixed?.(4) || 'unknown'}</Text>{s.status === 'ASSIGNED' && <Button label="Accept assignment" onPress={() => action(s.sosId, 'accept')} />}{s.status === 'ACCEPTED' && <Button label="Start route (EN_ROUTE)" onPress={() => action(s.sosId, 'EN_ROUTE')} />}{s.status === 'EN_ROUTE' && <Button label="Mark arrived" onPress={() => action(s.sosId, 'ARRIVED')} />}{s.status === 'ARRIVED' && <><Button label="Start rescue" onPress={() => action(s.sosId, 'RESCUING')} /><Button label="Person not found" onPress={() => action(s.sosId, 'USER_NOT_FOUND')} /></>}</Card>) : <Card><Text style={styles.subtitle}>No assignment is currently linked to your team. Standing by does not mean no emergency exists.</Text></Card>}</Screen>; }

function ShelterAdmin({ user, onLogout }: { user: User; onLogout: () => void }) { const mode = useNetwork(); const [shelter, setShelter] = useState<any>(); const [count, setCount] = useState('1'); const [note, setNote] = useState(''); const [requirements, setRequirements] = useState<any[]>([]); const [error, setError] = useState(''); const id = user.shelterId; async function load() { if (!id) return setError('No shelter is linked to this account.'); try { const [s, r] = await Promise.all([api.shelter(id), api.requirements(id)]); setShelter(s); setRequirements(r.requests || []); } catch (e) { setError(e instanceof Error ? e.message : 'Shelter unavailable'); } } useEffect(() => { load(); }, [id]); async function move(path: string) { const payload = { count: Math.abs(Number(count) || 0), note: note || null, expectedOccupancy: shelter?.occupancy }; if (!payload.count) return; try { if (mode === 'OFFLINE') { await queueShelterEvent({ shelterId: id, ...payload }); Alert.alert('Pending sync', 'Arrival/departure stored locally and not recorded at SETU yet.'); } else { setShelter(await api.updateShelter(id!, path, payload)); setNote(''); } } catch (e) { Alert.alert('Update rejected', e instanceof Error ? e.message : 'The shelter state was not changed.'); await load(); } } return <Screen><Header user={user} onLogout={onLogout} /><NetworkBanner mode={mode} /><Title eyebrow="Shelter management">{shelter?.name || 'Your shelter'}</Title>{error ? <ErrorState message={error} retry={load} /> : shelter ? <><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}><Card><Text style={styles.label}>CAPACITY</Text><Text style={styles.metric}>{shelter.capacity}</Text></Card><Card><Text style={styles.label}>OCCUPANCY</Text><Text style={styles.metric}>{shelter.occupancy}</Text></Card><Card><Text style={styles.label}>AVAILABLE (DERIVED)</Text><Text style={styles.metric}>{shelter.available}</Text></Card></View><Card><Status danger={['FULL', 'OVER_CAPACITY', 'CLOSED'].includes(shelter.status)}>{shelter.status}</Status><Text style={styles.subtitle}>{shelter.stalenessNotice || 'Freshness not provided'}</Text><Field value={count} onChangeText={setCount} placeholder="Number of people" keyboardType="number-pad" /><Field value={note} onChangeText={setNote} placeholder="Operational note" /><Button label="Record arrivals" onPress={() => move('arrivals')} /><Button label="Record departures" onPress={() => move('departures')} /></Card><Card><Text style={styles.label}>RESOURCE REQUIREMENTS</Text>{requirements.map((r) => <Text key={r.requestId} style={styles.subtitle}>{r.category}: {r.outstanding} {r.unit} outstanding</Text>)}</Card></> : <Loading />}</Screen>; }

function RoleApp({ user, onLogout }: { user: User; onLogout: () => void }) { if (user.role === 'USER') return <CitizenTabs user={user} onLogout={onLogout} />; if (user.role === 'SHELTER_ADMIN') return <EnhancedShelter user={user} onLogout={onLogout} />; if (user.role === 'RESCUE_LEADER') return <EnhancedLeader user={user} onLogout={onLogout} />; if (user.role === 'RESCUE_MEMBER') return <EnhancedMember user={user} onLogout={onLogout} />; return <Screen><Title eyebrow="Web portal required">This role stays on desktop.</Title><Text style={styles.subtitle}>Your account ({user.role}) does not have a mobile dashboard. Use the SETU web portal.</Text><Button label="Log out" onPress={onLogout} /></Screen>; }

export default function App() { const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { authStore.get().then(async (token) => { if (!token) return; try { setUser(await api.me()); } catch { await authStore.clear(); } finally { setLoading(false); } }); }, []); async function logout() { await deactivateRegisteredDevice().catch(() => undefined); await authStore.clear(); setUser(null); } if (loading) return <SafeAreaView style={{ flex: 1, backgroundColor: colors.paper }}><Loading /></SafeAreaView>; return <SafeAreaView style={{ flex: 1, backgroundColor: colors.paper }}><NavigationContainer ref={navigationRef}><NotificationBootstrap user={user} /><Stack.Navigator screenOptions={{ headerShown: false }}>{user ? <><Stack.Screen name="Role">{() => <RoleApp user={user} onLogout={logout} />}</Stack.Screen><Stack.Screen name="Notification">{({ route }: any) => <NotificationDetail kind={route.params?.screen === 'ShelterDetails' ? 'shelter' : route.params?.screen === 'SosDetails' || route.params?.screen === 'AssignmentDetails' ? 'sos' : 'alert'} id={route.params?.id} onBack={() => navigationRef.goBack()} />}</Stack.Screen></> : <Stack.Screen name="Auth">{() => <AuthScreen onAuthenticated={setUser} />}</Stack.Screen>}</Stack.Navigator></NavigationContainer></SafeAreaView>; }
