import React, { useEffect, useState } from 'react';
import { Alert, Linking, Text, View } from 'react-native';
import { api } from './api';
import { acquireLocation, setOperationalTeam, startOperationalLocation, stopOperationalLocation, SetuLocation } from './location';
import { NetworkMode, queueSos, subscribeNetwork, syncShelterQueue } from './offline';
import { OperationalMap } from './map';
import { Button, Card, colors, ErrorState, Field, Loading, NetworkBanner, Screen, Status, styles, Title } from './ui';

export function EnhancedCitizenSos() {
  const [mode, setMode] = useState<NetworkMode>('ONLINE'); const [location, setLocation] = useState<SetuLocation | null>(null); const [lat, setLat] = useState(''); const [lng, setLng] = useState(''); const [landmark, setLandmark] = useState(''); const [type, setType] = useState('TRAPPED'); const [people, setPeople] = useState('1'); const [description, setDescription] = useState(''); const [result, setResult] = useState<any>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { const unsubscribe = subscribeNetwork(setMode); acquireLocation().then((value) => { setLocation(value); if (value) { setLat(String(value.latitude)); setLng(String(value.longitude)); } }); return unsubscribe; }, []);
  function useManual() { const latitude = Number(lat); const longitude = Number(lng); if (!Number.isFinite(latitude) || latitude < -90 || latitude > 90 || !Number.isFinite(longitude) || longitude < -180 || longitude > 180) return setError('Enter valid latitude and longitude.'); setLocation({ latitude, longitude, accuracy: 500, timestamp: new Date().toISOString(), source: 'MANUAL', landmark: landmark || undefined }); setError(''); }
  async function send() { if (!location) return setError('A GPS, cached, or manually entered coordinate is required by the backend. Add a landmark to help teams search around an approximate point.'); const payload = { location: { ...location, landmark: landmark || location.landmark || undefined }, emergencyType: type, peopleCount: Number(people) || 1, description: description || null, landmark: landmark || null, networkStatus: mode, clientCreatedAt: new Date().toISOString(), clientRef: `mobile-${Date.now()}` }; setBusy(true); try { if (mode === 'OFFLINE') { await queueSos(payload); setResult({ status: 'QUEUED_OFFLINE', message: 'SOS saved locally. Transmission pending; SETU has not acknowledged it.' }); } else setResult(await api.createSos(payload)); } catch { await queueSos(payload); setResult({ status: 'QUEUED_OFFLINE', message: 'SOS saved locally. Transmission pending; SETU has not acknowledged it.' }); } finally { setBusy(false); } }
  return <Screen><NetworkBanner mode={mode} /><Title eyebrow="Emergency SOS">Send help without guessing your location.</Title><Card><Text style={styles.subtitle}>{location ? `${location.source} · ${location.accuracy ? `approximately ${Math.round(location.accuracy)}m` : 'accuracy unknown'}` : 'No digital location yet'}</Text><Button label="Try GPS / last known location" onPress={async () => setLocation(await acquireLocation())} /><Field value={lat} onChangeText={setLat} placeholder="Latitude (manual)" keyboardType="numeric" /><Field value={lng} onChangeText={setLng} placeholder="Longitude (manual)" keyboardType="numeric" /><Field value={landmark} onChangeText={setLandmark} placeholder="Landmark or address description" /><Button label="Use manual location" onPress={useManual} /></Card><Card><Field value={type} onChangeText={setType} placeholder="Emergency type, e.g. INJURED" /><Field value={people} onChangeText={setPeople} placeholder="People count" keyboardType="number-pad" /><Field value={description} onChangeText={setDescription} placeholder="What is happening? Optional" /><Button label={busy ? 'Transmitting...' : 'PRESS TO SEND SOS'} onPress={send} disabled={busy} danger /></Card>{error ? <Text style={styles.error}>{error}</Text> : null}{result && <Card><Status danger={!result.acknowledged}>{result.status}</Status><Text style={styles.subtitle}>{result.message || (result.acknowledged ? 'SOS sent successfully and acknowledged by SETU.' : 'Waiting for server acknowledgement.')}</Text>{result.sosId && <Text style={{ color: colors.primary, fontWeight: '800' }}>{result.sosId} · {result.priority}</Text>}</Card>}</Screen>;
}

export function EnhancedLeader({ user, onLogout }: any) {
  const [dashboard, setDashboard] = useState<any>(); const [queue, setQueue] = useState<any[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { try { const [d, q] = await Promise.all([api.rescueDashboard(), api.queue('?unassignedOnly=false')]); setDashboard(d); setQueue(q.sos || []); } catch (e) { setError(e instanceof Error ? e.message : 'Command centre unavailable'); } }
  useEffect(() => { load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, []);
  async function assign(item: any) { try { const rec = await api.recommendations(item.sosId); const team = rec.recommendations?.find((candidate: any) => candidate.assignable); if (!team) return Alert.alert('No available team', 'The backend returned no assignable team.'); setBusy(true); await api.assign(item.sosId, team.teamId); await load(); } catch (e) { Alert.alert('Assignment failed', e instanceof Error ? e.message : 'The server rejected the assignment.'); } finally { setBusy(false); } }
  const points = (dashboard?.mapMarkers || []).map((item: any) => ({ latitude: item.latitude, longitude: item.longitude, title: item.sosId, priority: item.priority, status: item.status, id: item.sosId }));
  return <Screen><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Title eyebrow="Rescue command">Operational picture</Title><Button label="Log out" onPress={onLogout} /></View>{error ? <ErrorState message={error} retry={load} /> : !dashboard ? <Loading /> : <><OperationalMap points={points} /><Card><Text style={styles.label}>LIVE BACKEND COUNTS</Text><Text style={styles.metric}>{dashboard.counts.totalActiveSos} active · {dashboard.counts.critical_P1} P1 · {dashboard.counts.unassigned} unassigned</Text><Text style={styles.subtitle}>Generated {String(dashboard.generatedAt || 'unknown')}. Missing data is not an all-clear.</Text></Card>{queue.map((item) => <Card key={item.sosId}><Text style={{ color: colors.primary, fontWeight: '800' }}>{item.sosId} · {item.priority}</Text><Status>{item.status}</Status><Text style={styles.subtitle}>{item.emergencyType} · {item.peopleCount} people · {item.injuredCount} injured</Text>{['PENDING', 'TIMEOUT', 'VERIFIED'].includes(item.status) && <Button label={busy ? 'Assigning...' : 'Assign backend recommendation'} onPress={() => assign(item)} disabled={busy} />}</Card>)}</>}</Screen>;
}

export function CitizenSosStatus() {
  const [cases, setCases] = useState<any[]>([]); const [selected, setSelected] = useState<any>(); const [timeline, setTimeline] = useState<any[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { try { const result = await api.mySos(); const next = result.sos || []; setCases(next); if (!selected && next[0]) setSelected(next[0]); } catch (e) { setError(e instanceof Error ? e.message : 'SOS status unavailable'); } }
  async function select(item: any) { setSelected(item); try { setTimeline((await api.timeline(item.sosId)).timeline || []); } catch (e) { setError(e instanceof Error ? e.message : 'Timeline unavailable'); } }
  useEffect(() => { load(); }, []);
  useEffect(() => { if (selected) select(selected); }, [selected?.sosId]);
  async function cancel() { if (!selected || busy) return; setBusy(true); try { setSelected(await api.cancelSos(selected.sosId)); await load(); } catch (e) { Alert.alert('Cancellation rejected', e instanceof Error ? e.message : 'The SOS was not changed.'); } finally { setBusy(false); } }
  return <Screen><Title eyebrow="SOS status">Confirmed case timeline</Title>{error ? <ErrorState message={error} retry={load} /> : !cases.length ? <Card><Text style={styles.subtitle}>No SOS records are associated with this account.</Text></Card> : <><Card>{cases.map((item) => <Button key={item.sosId} label={`${item.sosId} · ${item.status}`} onPress={() => select(item)} />)}</Card>{selected && <Card><Status danger={!selected.acknowledged}>{selected.status}</Status><Text style={styles.subtitle}>{selected.acknowledged ? 'Server acknowledged this SOS.' : 'Not acknowledged by SETU.'}</Text>{timeline.map((entry, index) => <Text key={entry.auditId || index} style={styles.subtitle}>{entry.action || entry.status || 'Recorded event'} · {String(entry.at || entry.createdAt || '')}</Text>)}{['CREATED', 'RECEIVED', 'VERIFIED', 'PENDING'].includes(selected.status) && <Button label={busy ? 'Cancelling...' : 'Cancel SOS'} onPress={cancel} disabled={busy} danger />}</Card>}</>}</Screen>;
}
