import React, { useEffect, useState } from 'react';
import { Alert, Linking, Text, View } from 'react-native';
import { api } from './api';
import { acquireLocation, startOperationalLocation, stopOperationalLocation } from './location';
import { jsonStore, SHELTER_QUEUE } from './storage';
import { NetworkMode, queueShelterEvent, subscribeNetwork, syncShelterQueue } from './offline';
import { OperationalMap } from './map';
import { Button, Card, colors, ErrorState, Field, Loading, NetworkBanner, Screen, Status, styles, Title } from './ui';

export function NotificationDetail({ kind, id, onBack }: { kind: 'alert' | 'sos' | 'shelter'; id?: string; onBack: () => void }) {
  const [data, setData] = useState<any>(); const [error, setError] = useState('');
  async function load() { try { if (!id) throw new Error('Notification target is missing'); setData(kind === 'sos' ? await api.sos(id) : kind === 'shelter' ? await api.shelter(id) : (await api.events()).events?.find((item: any) => item.eventId === id)); } catch (e) { setError(e instanceof Error ? e.message : 'Record unavailable'); } }
  useEffect(() => { load(); }, [id, kind]);
    return <Screen><Button label="Back" onPress={onBack} /><Title eyebrow="Notification target">{kind === 'sos' ? 'SOS detail' : kind === 'shelter' ? 'Shelter detail' : 'Official alert'}</Title>{error ? <ErrorState message={error} retry={load} /> : !data ? <Card><Text style={styles.subtitle}>This record is unavailable or you are not authorized to view it.</Text></Card> : <Card><Text style={{ color: colors.primary, fontWeight: '800' }}>{data.title || data.name || data.sosId || id}</Text><Status>{data.status || data.priority || 'RECEIVED'}</Status><Text style={styles.subtitle}>{data.message || data.description || data.fullNotice || data.instructions?.join('\n') || 'Record loaded from SETU.'}</Text></Card>}</Screen>;
}

export function EnhancedMember({ user, onLogout }: any) {
  const [cases, setCases] = useState<any[]>([]); const [reportFor, setReportFor] = useState<any>(); const [report, setReport] = useState<any>({ peopleRescued: '0', injuredTransported: '0', fatalities: '0', handedOverTo: '', victimConfirmation: true, victimConfirmationWaivedReason: '', observations: '' }); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  async function load() { try { setCases((await api.assigned()).sos || []); } catch (e) { setError(e instanceof Error ? e.message : 'Assignments unavailable'); } }
  useEffect(() => { load(); const timer = setInterval(load, 25000); return () => clearInterval(timer); }, []);
  useEffect(() => { const active = cases.some((item) => !['COMPLETED', 'CANCELLED_BY_USER'].includes(item.status)); if (active) { startOperationalLocation(async (location) => { if (user.teamId) await api.updateTeamLocation(user.teamId, location); }); } else stopOperationalLocation(); return () => stopOperationalLocation(); }, [cases, user.teamId]);
  async function status(item: any, next: string) { try { await api.status(item.sosId, next, await acquireLocation()); await load(); } catch (e) { Alert.alert('Action rejected', e instanceof Error ? e.message : 'The backend rejected this transition.'); } }
  async function submit() { if (!reportFor || submitting) return; if (!report.observations.trim() && Number(report.peopleRescued) === 0 && Number(report.fatalities) === 0) return Alert.alert('Report incomplete', 'Record people rescued, fatalities, or an operational observation.'); setSubmitting(true); try { await api.complete(reportFor.sosId, { ...report, peopleRescued: Number(report.peopleRescued) || 0, injuredTransported: Number(report.injuredTransported) || 0, fatalities: Number(report.fatalities) || 0, handedOverTo: report.handedOverTo || null, victimConfirmationWaivedReason: report.victimConfirmation ? null : report.victimConfirmationWaivedReason || 'Victim unable to confirm' }); setReportFor(null); await load(); } catch (e) { Alert.alert('Report failed', e instanceof Error ? e.message : 'Report was not acknowledged. Your entries remain on screen.'); } finally { setSubmitting(false); } }
  return <Screen><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Title eyebrow="Field operations">Assigned cases</Title><Button label="Log out" onPress={onLogout} /></View>{error ? <ErrorState message={error} retry={load} /> : cases.map((item) => <Card key={item.sosId}><Text style={{ color: colors.primary, fontWeight: '800' }}>{item.sosId} · {item.priority}</Text><Status>{item.status}</Status><Text style={styles.subtitle}>{item.emergencyType} · {item.peopleCount} people · {item.injuredCount} injured</Text><OperationalMap center={item.lastKnown || item.origin} points={[item.lastKnown || item.origin]} />{item.status === 'ASSIGNED' && <Button label="Accept assignment" onPress={() => status(item, 'ACCEPTED')} />}{item.status === 'ACCEPTED' && <Button label="Start route" onPress={() => status(item, 'EN_ROUTE')} />}{item.status === 'EN_ROUTE' && <><Button label="Mark arrived" onPress={() => status(item, 'ARRIVED')} /><Button label="Open suggested route" onPress={() => { const loc = item.lastKnown || item.origin; Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${loc.latitude},${loc.longitude}`); }} /></>}{item.status === 'ARRIVED' && <><Button label="Start rescue" onPress={() => status(item, 'RESCUING')} /><Button label="Person not found" onPress={() => status(item, 'USER_NOT_FOUND')} /></>}{['RESCUED', 'NOT_FOUND', 'ALREADY_RESCUED', 'FALSE_ALARM'].includes(item.status) && <Button label="Complete rescue report" onPress={() => setReportFor(item)} />}</Card>)}{reportFor && <Card><Title eyebrow="Structured report">{reportFor.sosId}</Title><Field value={report.peopleRescued} onChangeText={(value: string) => setReport({ ...report, peopleRescued: value })} placeholder="People rescued" keyboardType="number-pad" /><Field value={report.injuredTransported} onChangeText={(value: string) => setReport({ ...report, injuredTransported: value })} placeholder="Injured transported" keyboardType="number-pad" /><Field value={report.fatalities} onChangeText={(value: string) => setReport({ ...report, fatalities: value })} placeholder="Fatalities" keyboardType="number-pad" /><Field value={report.handedOverTo} onChangeText={(value: string) => setReport({ ...report, handedOverTo: value })} placeholder="Destination: shelter, hospital, safe location" /><Field value={report.observations} onChangeText={(value: string) => setReport({ ...report, observations: value })} placeholder="Search conducted / equipment / problems encountered" /><Button label="Submit report" onPress={submit} /><Button label="Keep draft" onPress={() => Alert.alert('Draft retained', 'The report remains open on this screen.')} /></Card>}</Screen>;
}

export function EnhancedShelter({ user, onLogout }: any) {
  const [mode, setMode] = useState<NetworkMode>('ONLINE'); const [syncStatus, setSyncStatus] = useState<'SYNCED' | 'SYNCING' | 'FAILED'>('SYNCED'); const [shelter, setShelter] = useState<any>(); const [shelters, setShelters] = useState<any[]>([]); const [count, setCount] = useState('1'); const [note, setNote] = useState(''); const [destination, setDestination] = useState(''); const [reason, setReason] = useState(''); const [transferCount, setTransferCount] = useState('1'); const [queueCount, setQueueCount] = useState(0); const [error, setError] = useState(''); const id = user.shelterId;
  async function load() { try { if (!id) throw new Error('No shelter is linked to this account'); const [s, list] = await Promise.all([api.shelter(id), api.shelters()]); setShelter(s); setShelters(list.shelters || []); setQueueCount((await jsonStore.get<any[]>(SHELTER_QUEUE, [])).filter((item) => item.shelterId === id).length); } catch (e) { setError(e instanceof Error ? e.message : 'Shelter unavailable'); } }
  useEffect(() => { load(); const unsubscribe = subscribeNetwork((next) => { setMode(next); if (next === 'ONLINE' && id) { setSyncStatus('SYNCING'); syncShelterQueue(id).then(() => { setSyncStatus('SYNCED'); return load(); }).catch(() => setSyncStatus('FAILED')); } }); return unsubscribe; }, [id]);
  async function move(path: string) { const payload = { shelterId: id, count: Math.abs(Number(count) || 0), note: note || null, expectedOccupancy: shelter?.occupancy, occurredAt: new Date().toISOString() }; if (!payload.count) return; try { if (mode === 'OFFLINE') { await queueShelterEvent(payload); setSyncStatus('SYNCING'); } else setShelter(await api.updateShelter(id, path, payload)); setNote(''); await load(); } catch (e) { setSyncStatus('FAILED'); Alert.alert('Update rejected', e instanceof Error ? e.message : 'Server conflict. No value was overwritten.'); await load(); } }
  async function sync() { setSyncStatus('SYNCING'); try { const result = await syncShelterQueue(id); setSyncStatus((result.rejected || []).length ? 'FAILED' : 'SYNCED'); Alert.alert('Sync result', `${result.applied} applied, ${(result.rejected || []).length} rejected. Rejected entries remain pending.`); await load(); } catch (e) { setSyncStatus('FAILED'); Alert.alert('Sync failed', e instanceof Error ? e.message : 'Logs remain pending on this device.'); } }
  async function transfer() { if (!destination || !reason || !Number(transferCount)) return Alert.alert('Transfer incomplete', 'Choose a destination, count, and reason.'); try { const result = await api.transfer(id, { toShelterId: destination, count: Number(transferCount), reason }); setShelter(result.from); setReason(''); await load(); } catch (e) { Alert.alert('Transfer rejected', e instanceof Error ? e.message : 'Destination capacity or status rejected this transfer.'); await load(); } }
  return <Screen><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Title eyebrow="Shelter operations">{shelter?.name || 'Your shelter'}</Title><Button label="Log out" onPress={onLogout} /></View><NetworkBanner mode={mode} />{error ? <ErrorState message={error} retry={load} /> : !shelter ? <Loading /> : <><Card><Text style={styles.label}>CAPACITY / OCCUPANCY / AVAILABLE</Text><Text style={styles.metric}>{shelter.capacity} / {shelter.occupancy} / {shelter.available}</Text><Status danger={['FULL', 'OVER_CAPACITY', 'CLOSED'].includes(shelter.status)}>{shelter.status}</Status><Text style={styles.subtitle}>{shelter.stalenessNotice || 'Freshness not provided'}</Text></Card><Card><Status danger={syncStatus === 'FAILED'}>Queue: {syncStatus}</Status><Field value={count} onChangeText={setCount} placeholder="People count" keyboardType="number-pad" /><Field value={note} onChangeText={setNote} placeholder="Operational note" /><Button label="Record arrivals" onPress={() => move('arrivals')} /><Button label="Record departures" onPress={() => move('departures')} />{queueCount > 0 && <Button label={`Sync ${queueCount} pending event(s)`} onPress={sync} />}</Card><Card><Title eyebrow="Audited transfer">Move people to another shelter</Title><Field value={destination} onChangeText={setDestination} placeholder={`Destination shelter ID (${shelters.filter((item) => item.shelterId !== id).map((item) => item.shelterId).join(', ')})`} /><Field value={transferCount} onChangeText={setTransferCount} placeholder="Number of people" keyboardType="number-pad" /><Field value={reason} onChangeText={setReason} placeholder="Reason" /><Button label="Create transfer" onPress={transfer} /></Card></>}</Screen>;
}

export function CitizenMap() { const [rows, setRows] = useState<any[]>([]); useEffect(() => { api.shelters().then((data) => setRows(data.shelters || [])).catch(() => undefined); }, []); return <Screen><Title eyebrow="Operational map">Shelters and current position</Title><OperationalMap points={rows.map((item) => ({ latitude: item.location?.latitude, longitude: item.location?.longitude, name: item.name, status: item.status, id: item.shelterId }))} /></Screen>; }
