import React from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { theme, colors } from './theme';

export { colors };
export function Screen({ children }: { children: React.ReactNode }) { return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.screen}>{children}</ScrollView>; }
export function Title({ eyebrow, children }: { eyebrow?: string; children: React.ReactNode }) { return <View><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{children}</Text></View>; }
export function Card({ children }: { children: React.ReactNode }) { return <View style={styles.card}>{children}</View>; }
export function Button({ label, onPress, disabled = false, danger = false }: { label: string; onPress: () => void; disabled?: boolean; danger?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.button, danger && styles.danger, disabled && styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>; }
export function Field({ value, onChangeText, placeholder, keyboardType = 'default', secureTextEntry = false }: any) { return <TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.textSubtle} keyboardType={keyboardType} secureTextEntry={secureTextEntry} style={styles.field} />; }
export function Status({ children, danger = false }: { children: React.ReactNode; danger?: boolean }) { const statusColor = typeof children === 'string' ? theme.status[children] : undefined; return <Text style={[styles.status, statusColor && { color: statusColor }, danger && styles.statusDanger]}>{children}</Text>; }
export function Loading() { return <ActivityIndicator color={colors.primary} size="large" style={{ margin: 30 }} />; }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <Card><Text style={styles.error}>{message}</Text><Button label="Retry" onPress={retry} /></Card>; }
export function NetworkBanner({ mode }: { mode: 'ONLINE' | 'DEGRADED' | 'OFFLINE' }) { return mode === 'ONLINE' ? null : <View style={styles.networkBanner}><Text style={styles.networkText}>{mode === 'OFFLINE' ? 'Offline: cached information only. No server action is confirmed.' : 'Degraded network: updates may be delayed.'}</Text></View>; }
export const styles = StyleSheet.create({ screen: { flexGrow: 1, backgroundColor: colors.background, padding: theme.spacing.page, gap: theme.spacing.section }, eyebrow: { color: colors.accent, fontWeight: '800', letterSpacing: theme.typography.label.letterSpacing, fontSize: theme.typography.label.fontSize, textTransform: 'uppercase' }, title: { color: colors.primary, fontSize: theme.typography.title.fontSize, lineHeight: theme.typography.title.lineHeight, fontWeight: theme.typography.title.fontWeight, marginTop: 4 }, subtitle: { color: colors.textMuted, fontSize: theme.typography.body.fontSize, lineHeight: theme.typography.body.lineHeight }, card: { backgroundColor: colors.surface, borderRadius: theme.radius.card, borderWidth: 1, borderColor: colors.border, padding: theme.spacing.card, gap: theme.spacing.row, elevation: theme.elevation.card }, button: { minHeight: theme.controls.buttonHeight, backgroundColor: colors.primary, borderRadius: theme.radius.control, paddingVertical: 14, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' }, danger: { backgroundColor: colors.danger }, disabled: { opacity: 0.45 }, buttonText: { color: colors.surface, fontWeight: '800', textAlign: 'center' }, field: { minHeight: theme.controls.inputHeight, backgroundColor: colors.surface, borderColor: colors.input, borderWidth: 1, borderRadius: theme.radius.control, padding: 13, color: colors.text, fontSize: theme.typography.body.fontSize }, status: { color: colors.primary, fontWeight: '800', textTransform: 'uppercase', fontSize: theme.typography.label.fontSize }, statusDanger: { color: colors.danger }, metric: { color: colors.primary, fontSize: 25, fontWeight: '800' }, label: { color: colors.textSubtle, fontSize: theme.typography.label.fontSize, fontWeight: '700', letterSpacing: 0.8 }, error: { color: colors.danger, lineHeight: 20 }, networkBanner: { backgroundColor: colors.warningSurface, padding: 10, borderRadius: theme.radius.control, borderWidth: 1, borderColor: colors.warningBorder }, networkText: { color: colors.warningText, fontWeight: '700' } });
